export const BUTTONS = [{
    id:"clear",
    value:'AC',
    type:"OP",
    display:'AC'
    },{
    id:"divide",
    value:'/',
    type:"OP",
    display:'/'
    },{
    id:"seven",
    value:'7',
    type:"NUM",
    display:'7'
    },{
    id:"eight",
    value:'8',
    type:"NUM",
    display:'8'
    },{
    id:"nine",
    value:'9',
    type:"NUM",
    display:'9'
    },{
    id:"multiply",
    value:'*',
    type:"OP",
    display:'X'
    },{
    id:"four",
    value:'4',
    type:"NUM",
    display:'4'
    },{
    id:"five",
    value:'5',
    type:"NUM",
    display:'5'
    },{
    id:"six",
    value:'6',
    type:"NUM",
    display:'6'
    },{
    id:"subtract",
    value:'-',
    type:"OP",
    display:'-'
    },{
    id:"one",
    value:'1',
    type:"NUM",
    display:'1'
    },{
    id:"two",
    value:'2',
    type:"NUM",
    display:'2'
    },{
    id:"three",
    value:'3',
    type:"NUM",
    display:'3'
    },{
    id:"add",
    value:'+',
    type:"OP",
    display:'+'
    },{
    id:"zero",
    value:'0',
    type:"NUM",
    display:'0'
    },{
    id:"decimal",
    value:'.',
    type:"OP",
    display:'.'
    },{
    id:"equals",
    value:'=',
    type:"OP",
    display:'='
    }];
